global:
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
    - targets: [prometheus:9090']    # localhost

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'       # node
    static_configs:
    - targets: ['node_exporter:9100']

#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana Cloud Access Policy Token>'
